FROM rockylinux:9

# Install build dependencies
RUN dnf install -y epel-release && dnf update -y && \
    dnf groupinstall -y "Development Tools" && \
    dnf install -y \
    cmake \
    gcc-c++ \
    rpm-build \
    rpmdevtools \
    perl-FindBin \
    perl-devel

# Set working directory
WORKDIR /build

# Copy build scripts and source
COPY . /build
RUN chmod +x /build/scripts/*

WORKDIR /build/openssl-1.1.1w

RUN ./config --prefix=/opt/openssl/1.1.1 \
--openssldir=/opt/openssl/1.1.1 \
no-ssl3 shared linux-x86_64 && make -j$(nproc) &&  make install_sw

WORKDIR /build/openssl-3.0.11

RUN ./config --prefix=/opt/openssl/3.0.11 \
--openssldir=/opt/openssl/3.0.11 \
no-ssl3 shared linux-x86_64 && make -j$(nproc) &&  make install_sw

CMD ["/build/scripts/build-all.sh"]